---
- include: setup.yml
  tags:
    - prometheus_install
    - prometheus_configure
    - prometheus_run

- include: install.yml
  become: true
  tags: prometheus_install

- include: configure.yml
  become: true
  tags: prometheus_configure

- name: Start prometheus service
  service:
    name: prometheus
    state: started
    enabled: yes
  tags: prometheus_run

- name: Check if prometheus is accessible
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200