---
- name: restart the prometheus pushgateway service
  become: true
  systemd: 
    daemon_reload: true
    name: "{{ service_name }}"
    state: restarted
  listen: event_restart_prometheus

- name: reload systemd
  command: systemctl daemon-reload
  listen: reload_systemd